### PR TITLE
Add RLMArray+Utilities

### PR DESCRIPTION
**Pull request by yuuki1224**

### CODE REVIEW

**Comment by bigfish24** [comment]
I think the better way to do this would be:

``` objc
- (BOOL)containsObject:(RLMObject *)anObject
{
    if ([self indexOfObject:anObject] != NSNotFound) {
        return YES;
    }

    return NO;
}
```

Also, the documentation still reads:

> Retrieve the primary key for a given RLMObject

**Comment by yuuki1224** [comment]
@bigfish24 OK, I've fixed!

**Comment by bigfish24** [comment]
:+1: !

**Comment by nanoxd** [comment]
I found a problem with this change when `use_frameworks!` is set in the Podfile. Submitted #2 to fix it

**Pull request merged**
